import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {
  Button,
  Heading,
  Text,
  Box,
  FormControl,
  FormLabel,
  FormErrorMessage,
  FormHelperText,
  Input,
} from "@chakra-ui/react"
import { useSpring } from '@react-spring/web'

const CenteredBox = ({ children }) => (
  <Box display="flex" flexDirection="column" alignItems="center">
    {children}
  </Box>
)

const JoinForm = () => (
  <FormControl id="first-name">
    <Box>
      <FormLabel>Name</FormLabel>
      <Input placeholder="Rupert Pupkin" />
    </Box>
    <Box marginTop={3}>
      <FormLabel>Phone</FormLabel>
      <Input placeholder="6238662766" />
    </Box>
    <Box marginTop={3} float="right" aria-disabled={true}>
      <Button colorScheme="red">Join</Button>
    </Box>
  </FormControl>
)

// 
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Box padding={10} background="white" sx={{
          borderRadius: '20px'
        }}>
          <CenteredBox>
            <Heading>The Bad Movie Club</Heading>
            <Text fontSize="xl">NYC Summer 2021</Text>
            <Text fontSize="lg">Every 1st Thursday</Text>
          </CenteredBox>
          <Box marginTop={5}>
            <CenteredBox>
              <JoinForm />
            </CenteredBox>
          </Box>
        </Box>
      </main>

      <footer className={styles.footer}>
        {/* <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a> */}
      </footer>
    </div >
  )
}
